travis:
  secure:
    BINSTAR_TOKEN: ib9xt3aRI27hGOknFaGwBoRE7WuMC5otdzR3du4mWUnRA1RYxRwNpbOAmRjYnecORXDgBZpDeaQ/1lMBkaHbQpHC5RS6MOZvORv0GX8+KIrYS0yqYZnFlPMjp3ky/husreMAJa3UeQl7m82RkP2hOUexCtkvDbftpodfuoONcR1geJFgRmbU2sfvWiHgL2cUBpbOFyVxyhW617mFtF5Z8ikOuq3M3Yw0DphQVtXUQNISziO3nwQaXP1py2hZMBRExb2fo6wmUBvDvt/nDYAtOVNrTXwl42A7LqxB9sfOt2vkLdnARCVWkbDkSs8mJ7C/veSPKa3YgeDEoorQ2oXiKqBe0ccHNEYMHtdgWEZVqDIx9ILoQPObzUZ3PZk5VS8xwxOW/JhH54nl48CvN3fl3DKiy1s+YzUi4VOnh7Vvkp6xLODECv00j07x5u93aZBlU2qJRKnmfHVFqqQTTcuCmukPKV79+NYo7CIUXVoZKU3lgMh9L5Pbefsk+yyxh/uc9ccE9z2uTgD9KeVf7DgbgG21zoCHOwBULHUsrTmbw/0BROx28XVx0aLLr/zlIbJEocWTDVxCcFLqm8eP+YDJqpizSOO+8hhYIdmtg+ImR1xBYrQ+D8TLLLFxxwdpkPPymKKBZaTUXbUPNkE/nITuBsaAa3F2IUObDKg8Jo8jLQc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
